
/**
 * Lookup map for numeric state key IDs.
 *
 * Add new entries here as files are migrated away from `$NN_STATE_KEY` imports.
 */
const STATE_KEY = {
  '1': 'newVideoUrlForm',
  '2': 'newVideoUrlDialog',
  '3': 'newBookmarkFromUrlLinkState',
  '4': 'newYouTubeBookmarkForm',
  '5': 'editYouTubeBookmarkForm',
  '6': 'newYouTubeBookmarkDialog',
  '7': 'editYouTubeBookmarkDialog',
  '8': 'newRumbleBookmarkDialog',
  '9': 'newRumbleBookmarkForm',
  '10': 'editRumbleBookmarkForm',
  '11': 'editRumbleBookmarkDialog',
  '12': 'newVimeoBookmarkForm',
  '13': 'editVimeoBookmarkForm',
  '14': 'newVimeoBookmarkDialog',
  '15': 'editVimeoBookmarkDialog',
  '16': 'newOdyseeBookmarkDialog',
  '17': 'newOdyseeBookmarkForm',
  '18': 'editOdyseeBookmarkForm',
  '19': 'newDailyBookmarkForm',
  '20': 'editDailyBookmarkForm',
  '21': 'newDailyBookmarkDialog',
  '22': 'editDailyBookmarkDialog',
  '23': 'editOdyseeBookmarkDialog',
  '24': 'newFacebookBookmarkForm',
  '25': 'editFacebookBookmarkForm',
  '26': 'newFacebookBookmarkDialog',
  '27': 'editFacebookBookmarkDialog',
  '28': 'newUnknownBookmarkForm',
  '29': 'editUnknownBookmarkForm',
  '30': 'newUnknownBookmarkDialog',
  '31': 'editUnknownBookmarkDialog',
  '32': 'signInDialog',
  '33': 'registerDialog',
  '34': 'deleteBookmarkDialog',
  '35': 'clientAlertDialog',
  '36': 'newTwitchBookmarkDialog',
  '37': 'editTwitchBookmarkDialog',
  '38': 'newTwitchBookmarkForm',
  '39': 'editTwitchBookmarkForm',
  '40': 'research-app',
  '41': 'signInForm',
  '42': 'sign-in',
  '43': 'dev-signed-In',
  '44': 'dev-install',
  '45': 'devTestThumbnailForm',
  '46': 'dev-test-thumbnail',
  '47': 'devInstallForm',
  '48': 'default-errors-view',
  '49': 'devSetAuthorizationKeyForm',
  '50': 'devSetAuthorizationUrlForm',
  '51': 'listing/:id',
  '52': '<taken>',
  '53': 'admin-readable',
  '54': 'devTestRumbleRegexpForm',
  '55': 'admin-config-app',
  '56': 'dev-test-rumble-regexp',
  '57': 'devTestUnknownRegexpForm',
  '58': 'dev-test-unknown-regexp',
  '59': 'dev-twitch-input-client-id',
  '60': 'devTwitchInputClientIdForm',
  '61': 'save-config-value',
  '62': 'devSaveConfigValueForm',
  '63': 'researchPageAppbar',
  '64': 'responseAlertDialog',
  '65': 'alertDialog',
  '66': 'powerLogoutLink',
  '67': 'powerSignInLink',
  '68': 'confirmLogoutDialog',
  '69': 'newUserForm',
  '70': 'listing',
  '71': 'listingPageAppbar',
  '72': 'signup',
  '73': 'defaultPageAppbar',
  '74': 'new-user',
  '75': 'user',
  '76': 'searchModeUnavailableDialog',
  '77': 'bookmarkPublishUnavailableDialog',
  '78': 'bookmarkEditPublishSwitchDummy',
  '79': 'bookmarkEditPublishSwitch',
  '80': 'account',
  '81': 'accountPageAppbar',
  '82': 'editUserForm',
  '83': 'generic-not-found-page',
  '84': 'confirmDeleteAccountDialog',
  '85': 'passwordRecoveryDialog',
  '86': 'passwordRecoveryForm',
  '87': 'feedbackDialog',
  '88': 'feedbackForm',
  '89': 'resetPasswordForm',
  '90': 'reset-password',
  '91': 'privacy-policy',
} as const

export type TStateKey = typeof STATE_KEY[keyof typeof STATE_KEY]

export default STATE_KEY